### ISSUE TITLE
Printer froze Player

### ISSUE THREAD

**Issue by LettyR** [WaypointRP/wp-printer#4]
Hey there ^^

I use QB-Core Framework with ox-lib and try to integrate wp-printer. Without qb-print.Yes, i uncomment the ox-lib in the fx-manifest.
I had trouble to use the printer. As soon i add a Link, Players get frozen and needs to relog.
The Printer is gone.It stays not in place or go back into the Invetory.
Any hint´s for me ? I keep searching about what i do wrong, but can´t figuerd it out.
So - thanks for helping me out :)

**Comment by BackSH00TER** [comment]
@LettyR I'm not sure I fully follow where the issue is happening. 

> As soon i add a Link, Players get frozen and needs to relog.

Check the F8 console on the client when this happens. Also check the server logs. If there are relevant errors please share them. 

Does this happen with every type of link or only specific ones?

> The Printer is gone.It stays not in place or go back into the Invetory.

I'm not sure what you mean by this. When you use the printer you place it as an item on the ground, this also removes it from your inventory. You have to pick the printer back up to get the printer item back in your inventory. 

Also if you have a video repro of the issue that might help me in assisting you as well

**Comment by LettyR** [comment]
Sorry for late Answer. The Problem solved by itself.
It works know how it should.
So - Sorry for Disturbing and thanks for fast Respond :)

**Comment by LettyR** [comment]
Sorry for late Answer. The Problem solved by itself.
It works know how it should.
So - Sorry for Disturbing and thanks for fast Respond :)
